version: '3.8'

services:
  db:
    build: ./database
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contrasena
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always

  app:
    build: ./app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://usuario:contrasena@db/mi_base_de_datos
    restart: always

volumes:
  dbdata: